CXXFLAGS = -g -I/usr/local/include/opencv4 -I/usr/include/python3.9
LDFLAGS = -L/usr/local/lib
LDLIBS = -lopencv_calib3d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_core -lpython3.9 -lboost_program_options
